"""empty message

Revision ID: 1982e678d403
Revises: 6fcd99f57310
Create Date: 2019-06-01 17:27:53.120412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1982e678d403'
down_revision = '6fcd99f57310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ImageLocation', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ImageLocation')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_non_trans_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('ImageLoc_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ingredients', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ImageLoc_id'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['product_non_trans_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_translation')
    op.drop_table('product')
    op.drop_table('picture')
    op.drop_table('language')
    # ### end Alembic commands ###
